# Valid TOML config file
data-path="/node/data/"

# Network
bootnodes=["enode://202bccd94960181c17dde7cc03f62f80793ae192c1384b1f6226b84f0aac9e6caf2c74ea20d8888edf6ba7a80ced326491e68e88014e6d08f3b5011c7dcad9f9@172.16.239.11:30309"]

# Chain
genesis-file="/node/genesis.json"

# port
p2p-port="30309"
rpc-http-port="8545"

rpc-http-enabled=true
host-allowlist=["*"]
rpc-http-cors-origins=["*"]
"
rpc-http-api=["EEA","WEB3","ETH","NET","PRIV","PERM","IBFT","TXPOOL"]
rpc-ws-api=["EEA","WEB3","ETH","NET","PRIV","PERM","IBFT","TXPOOL"]

# OFF, FATAL, ERROR, WARN, INFO, DEBUG, TRACE, ALL
logging="INFO"