# Valid TOML config file
data-path="/node/data/"

# Network
bootnodes=["enode://6c0c48a3cc1a9dca153ad1376bd7b38184f61c79413b9bfc54e8d67c2944951ad128941cda93411c60cb5e0a36d4cd2c913d926bb08d37e0ba12658c1654205c@127.0.0.1:50505"]

# Chain
genesis-file="/node/genesis.json"

# port
p2p-port=50505
rpc-http-port=8545

rpc-http-enabled=true
rpc-http-api=["ETH","NET","IBFT","WEB3"]
host-allowlist=["*"]
rpc-http-cors-origins=["*"]

logging="ALL"